server:
  port: 8072
  
spring:
  h2:
    console:
      enabled: true  
      path: /h2
  datasource:
    url: jdbc:h2:~/test
    
#    
#  security:
#    user:
#      name: prasad
#      password: prasad
    
      